Repository maqalaqil/foodna, pull requests merged in 2021-04, with the labels that each got.

#51 Claim meal component
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.test.js
  src/components/ClaimMeal/ClaimMeal.css
  src/components/ClaimMeal/ClaimMeal.jsx
  src/firebase.js
Labels: enhancement

#47 Google OAuth added
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/components/OAuth/Login.jsx
  src/components/OAuth/Logout.jsx
  src/components/OAuth/OAuth.test.js
  src/components/OAuth/__snapshots__/OAuth.test.js.snap
  src/utils/refreshToken.js
Labels: enhancement

#34 Info component
  package-lock.json
  package.json
  public/img/info1.jpg
  public/img/info2.jpg
  public/img/info3.jpg
  src/components/InfoComponent/InfoComponent.css
  src/components/InfoComponent/InfoComponent.jsx
  src/components/InfoComponent/InfoComponent.test.js
  src/components/InfoComponent/__snapshots__/InfoComponent.test.js.snap
Labels: enhancement

#55 CSS fixes
  src/components/ClaimMeal/ClaimMeal.css
  src/components/ClaimMeal/ClaimMeal.jsx
  src/components/HeroComponent/HeroComponent.css
  src/components/HeroComponent/HeroComponent.jsx
  src/components/HeroComponent/__snapshots__/HeroComponent.test.js.snap
  src/components/InfoComponent/InfoComponent.css
  src/components/InfoComponent/InfoComponent.jsx
  src/components/InfoComponent/__snapshots__/InfoComponent.test.js.snap
  src/components/NarrowCta/NarrowCta.css
  src/components/NarrowCta/NarrowCta.jsx
  src/components/NarrowCta/__snapshots__/NarrowCta.test.js.snap
Labels: bug

#19 Build: Prepare_The_Bootstrap
  package.json
  src/App.js
  src/App.scss
  src/style/_variables.scss
  yarn.lock
Labels: Preparations

#59 Build: Testimonials_component
  src/App.js
  src/components/Testimonials/Testimonial.jsx
  src/components/Testimonials/Testimonial.scss
  src/components/Testimonials/Testimonials.jsx
  src/components/Testimonials/Testimonials.test.jsx
  src/components/Testimonials/__snapshots__/Testimonials.test.jsx.snap
  src/components/Testimonials/data.json
  src/dist/img/TA.jpg
  src/dist/img/TA1.jpg
Labels: enhancement

#49 Footer Component
  package.json
  src/components/Footer/Footer.jsx
  src/foodnaLogo.png
  src/index.js
  yarn.lock
Labels: enhancement

#50 Build: Feature_component
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/components/features/Feature.jsx
  src/components/features/Features.jsx
  src/components/features/Features.scss
  src/components/features/Features.test.jsx
  src/components/features/__snapshots__/Features.test.jsx.snap
  src/components/features/data.json
  src/dist/img/Media.png
  src/dist/img/Media1.png
  src/dist/img/Media2.png
  yarn.lock
Labels: enhancement
